name: flutter_eco_supabase
description: "A nature-focused conservation app powered by Supabase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  file_picker: ^8.0.0
  shared_preferences: ^2.3.5
  intl: ^0.19.0
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  model_viewer_plus: ^1.7.0
  arcore_flutter_plugin: ^0.1.0
  permission_handler: ^11.0.0
  flutter_unity_widget: ^2022.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png
    - assets/logo2.png
    - assets/red_rose.glb

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

  