name: flutter_eco_supabase
description: "A nature-focused conservation app powered by Supabase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # Swapping Firebase for Supabase
  supabase_flutter: ^2.6.0 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png  # Matches the folder and file shown in your explorer