name: flutter_eco_supabase
description: "A nature-focused conservation app powered by Supabase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  provider: ^6.1.1 # Added here and aligned correctly

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo1.png
    - assets/logo2.png
