org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=22
unityProjectPath=C:/Users/Althea/ARGreenAtlas_6.3vs
unity.projectPath=C:/Users/Althea/ARGreenAtlas_6.3vs
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=25
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.greenatlas.unityar
unity.abiFilters=armeabi-v7a,arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.greenatlas.unityar
unity.agpVersion=9.0.0
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.3.21f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.3.21f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.3.21f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.r8.strictFullModeForKeepRules=false
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never