// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFI8ZfKX9NFPgZLD--tdUyxXxZTjcBZs',
    appId: '1:975050737940:web:ab7017be5d3c65a8acda01',
    messagingSenderId: '975050737940',
    projectId: 'greenatlas-7a8eb',
    authDomain: 'greenatlas-7a8eb.firebaseapp.com',
    storageBucket: 'greenatlas-7a8eb.firebasestorage.app',
    measurementId: 'G-S17B43V2JD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIsiNecdFLgU2HlpYjIdtUjbXhlHOg0_0',
    appId: '1:975050737940:ios:6e430416fa7bd569acda01',
    messagingSenderId: '975050737940',
    projectId: 'greenatlas-7a8eb',
    storageBucket: 'greenatlas-7a8eb.firebasestorage.app',
    iosBundleId: 'com.example.greenatlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIsiNecdFLgU2HlpYjIdtUjbXhlHOg0_0',
    appId: '1:975050737940:ios:6e430416fa7bd569acda01',
    messagingSenderId: '975050737940',
    projectId: 'greenatlas-7a8eb',
    storageBucket: 'greenatlas-7a8eb.firebasestorage.app',
    iosBundleId: 'com.example.greenatlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEFI8ZfKX9NFPgZLD--tdUyxXxZTjcBZs',
    appId: '1:975050737940:web:230bad9188659427acda01',
    messagingSenderId: '975050737940',
    projectId: 'greenatlas-7a8eb',
    authDomain: 'greenatlas-7a8eb.firebaseapp.com',
    storageBucket: 'greenatlas-7a8eb.firebasestorage.app',
    measurementId: 'G-12HNQ3EKGY',
  );
}
